#ifndef GATES_H
#define GATES_H

#define GATE_END        16
#define GATE_START      1
#define GATE_UPPER_PIN  2
#define GATE_LOWER_PIN  13

#define GATES_PER_ROW 8

enum {
    G_AND,
    G_OR,
    G_XOR,
    G_BUFFER,
    G_GATE_END,
    G_NEGATE,
    G_WIRE_LEFTUP,
    G_WIRE_LEFTDOWN,
    G_WIRE_DOWNRIGHT,
    G_WIRE_UPRIGHT,
    G_WIRE_CONNECT_UPPER_DOWN,
    G_WIRE_CONNECT_LOWER_DOWN,
    G_WIRE_CONNECT_UPPER_UP,
    G_WIRE_CONNECT_LOWER_UP,
    G_WIRE_LOWER,
    G_WIRE_UPPER,
    G_WIRE_CONNECT_LOWER_STRAIGHT,
    G_WIRE_CONNECT_UPPER_STRAIGHT,
    G_WIRE_CROSS,

    G_WIRE_AMOUNT
};

#endif
